general {
  # This prevents hypridle from locking when the monitor turns back on
  ignore_dbus_inhibit = false
}

listener {
  timeout = 600
  on-timeout = systemctl suspend # Or systemctl suspend-then-hibernate
}
